### PR TITLE
Fixes

### LINKED ISSUE #16: Update Handling
The message part needs to be changed to:

- cache in guild.channels.get(id).messages if guild is enabled
- cache in cache.channels.get(id).messages if guild is disabled
- fetcher fetching properly based on where the message would be in:
    - fetching channel only if channel is not a guild channel or if cacheInMemory.guilds is true and guild is cached but not the channel
    - fetching guild if cacheInMemory.guilds is true and this channel is a guild channel and guild isn't cached

### PR DESCRIPTION
**Pull request by deepsarda**
Fixes #16 except for guildCreate being emitted

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -754,7 +754,7 @@ export function createProxyCache<
 
       return;
     },
-    set: async function (message: T["message"]): Promise<void> {
+    set: async function (message: Message /*<T["message"]>*/): Promise<void> {
```
Comment (Skillz4Killz) [inline index.ts]: I dont think this should be changed? what was the reasoning behind it

File: index.ts [hunk 2]
```diff
@@ -763,21 +763,24 @@ export function createProxyCache<
...
-        if (options.cacheInMemory?.guilds) {
+        if (options.cacheInMemory?.channels) {
           if (message.channelId)
             bot.cache.messages.channelIDs.set(message.id, message.channelId);
 
-          const guildID = bot.cache.messages.channelIDs.get(message.id);
-          if (guildID) {
-            const guild = bot.cache.guilds.memory.get(guildID) ?? await fetchers.fetchGuild(guildID, true);
-            if (guild) guild.messages.set(message.id, message);
+          const channelId = bot.cache.messages.channelIDs.get(message.id);
```
Comment (Skillz4Killz) [inline index.ts]:
```suggestion
          const channelId = message.channelId ?? bot.cache.messages.channelIDs.get(message.id);
```

File: index.ts [hunk 3]
```diff
@@ -763,21 +763,24 @@ export function createProxyCache<
...
+          if (channelId) {
+            const channel = await bot.cache.channels.get(channelId) ?? await fetchers.fetchChannel(channelId,message.guildId);
+            if (channel){
+              channel.messages.set(message.id, message);
+              bot.cache.channels.set(channel);
```
Comment (Skillz4Killz) [inline index.ts:775]: I dont believe this line is necessary

File: index.ts (hunk 1 above)
Comment (Skillz4Killz) [inline index.ts]:
```suggestion
    set: async function (message: <T["message"]>): Promise<void> {
```

**Review by Skillz4Killz — APPROVED** [review]
